version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dinov3-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_NAME=${MODEL_NAME:-facebook/dinov2-base}
      - HF_TOKEN=${HF_TOKEN:-}
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - dinov3-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dinov3-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - dinov3-network

networks:
  dinov3-network:
    driver: bridge
