version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: gc-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - gc-network
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gc-gradio
    ports:
      - "7860:7860"
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - gc-network
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./config:/app/config
      - ./src:/app/src

volumes:
  ollama_data:

networks:
  gc-network:
    driver: bridge
